# Generated by Django 6.0.3 on 2026-03-28 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(choices=[('quimioterapia', 'Quimioterapia'), ('radioterapia', 'Radioterapia'), ('hormonoterapia', 'Hormonoterapia'), ('cirugia', 'Post-cirugía'), ('general', 'General')], max_length=20, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del plan')),
                ('recomendacion', models.TextField(verbose_name='Recomendaciones generales')),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Planes Nutricionales',
            },
        ),
        migrations.CreateModel(
            name='SugerenciaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(choices=[('nauseas', 'Náuseas y vómitos'), ('fatiga', 'Fatiga / pérdida de apetito'), ('diarrea', 'Diarrea o estreñimiento'), ('boca_seca', 'Boca seca y llagas'), ('cambio_gusto', 'Cambios en el gusto'), ('general', 'General')], max_length=20)),
                ('sugerencia', models.TextField(verbose_name='Sugerencia de alimentos')),
                ('alimentos', models.TextField(help_text='Uno por línea', verbose_name='Lista de alimentos recomendados')),
            ],
            options={
                'verbose_name': 'Sugerencia Rápida',
                'verbose_name_plural': 'Sugerencias Rápidas',
            },
        ),
        migrations.CreateModel(
            name='RegistroNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(choices=[('nauseas', 'Náuseas y vómitos'), ('fatiga', 'Fatiga / pérdida de apetito'), ('diarrea', 'Diarrea o estreñimiento'), ('boca_seca', 'Boca seca y llagas'), ('cambio_gusto', 'Cambios en el gusto'), ('general', 'General')], default='general', max_length=20)),
                ('nota', models.TextField(blank=True, verbose_name='Nota del día')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_nutricionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Nutricional',
                'ordering': ['-fecha'],
            },
        ),
    ]
