# Generated by Django 6.0.3 on 2026-03-27 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dosis')),
                ('unidad', models.CharField(choices=[('capsula', 'Cápsula'), ('tableta', 'Tableta'), ('mg', 'mg'), ('ml', 'ml'), ('unidad', 'Unidad')], default='tableta', max_length=10, verbose_name='Unidad')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('cada_x_horas', 'Recurrente (Cada X horas)'), ('prn', 'Según Necesidad (PRN)')], default='diaria', max_length=20, verbose_name='Frecuencia')),
                ('cada_x_horas', models.PositiveIntegerField(blank=True, help_text='Solo si la frecuencia es "Cada X horas"', null=True, verbose_name='Cada cuántas horas')),
                ('hora_toma', models.TimeField(verbose_name='Hora de toma (formato 24h)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['hora_toma'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('tomada', 'Tomada'), ('omitida', 'Omitida'), ('tarde', 'Tomada tarde')], max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True, verbose_name='Síntoma / nota')),
                ('alarma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='alarma.alarma')),
            ],
            options={
                'verbose_name': 'Historial de dosis',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
