# Generated by Django 6.0.3 on 2026-04-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='dosis',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Dosis'),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='hora_toma',
            field=models.TimeField(verbose_name='Hora de toma'),
        ),
        migrations.AlterField(
            model_name='alarma',
            name='unidad',
            field=models.CharField(choices=[('ml', 'ml (mililitros)'), ('mg', 'mg (miligramos)'), ('comprimido', 'Comprimido'), ('capsula', 'Cápsula'), ('gota', 'Gota'), ('unidad', 'Unidad'), ('sobre', 'Sobre'), ('ampolla', 'Ampolla')], default='comprimido', max_length=15, verbose_name='Unidad'),
        ),
    ]
