# Generated by Django 6.0.3 on 2026-03-27 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('quimioterapia', 'Quimioterapia'), ('radioterapia', 'Radioterapia'), ('examenes', 'Exámenes de laboratorio'), ('nutricion', 'Nutrición'), ('psicologia', 'Psicología'), ('oncologia', 'Oncología'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de cita')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('profesional', models.CharField(blank=True, max_length=200, verbose_name='Profesional')),
                ('recordatorio', models.CharField(choices=[('24h', '24 horas antes'), ('2h', '2 horas antes'), ('correo', 'Por correo'), ('ninguno', 'Sin recordatorio')], default='24h', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
