# Generated by Django 6.0.3 on 2026-03-28 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_energia', models.CharField(choices=[('alta', 'Alta Energía'), ('media', 'Energía Media'), ('dificil', 'Día Difícil')], max_length=10, verbose_name='Nivel de energía')),
                ('duracion_min', models.PositiveIntegerField(default=15, verbose_name='Duración (minutos)')),
                ('completada', models.BooleanField(default=False)),
                ('nota', models.TextField(blank=True, verbose_name='Cómo me sentí')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_ejercicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de ejercicio',
                'verbose_name_plural': 'Sesiones de ejercicio',
                'ordering': ['-fecha'],
            },
        ),
    ]
