# Generated by Django 6.0.3 on 2026-03-27 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres.')], verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'El precio debe ser mayor a 0.'), django.core.validators.MaxValueValidator(9999999, 'El precio máximo permitido es $9.999.999.')], verbose_name='Precio (COP)')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'El stock no puede ser negativo.')], verbose_name='Stock')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('uso_recomendado', models.CharField(choices=[('nauseas', 'Para náuseas'), ('fatiga', 'Para fatiga'), ('dolor', 'Para dolor'), ('nutricion', 'Nutrición'), ('higiene', 'Higiene y cuidado'), ('general', 'Uso general')], default='general', max_length=20, verbose_name='Uso recomendado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Dejar vacío si el producto no vence.', null=True, verbose_name='Fecha de vencimiento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('nombre', 'categoria')},
            },
        ),
    ]
